// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace SINners.Models
{
    using Newtonsoft.Json;
    using System;

    public partial class ApplicationUserFavoriteGroup
    {
        /// <summary>
        /// Initializes a new instance of the ApplicationUserFavoriteGroup
        /// class.
        /// </summary>
        public ApplicationUserFavoriteGroup()
        {
        }

        /// <summary>
        /// Initializes a new instance of the ApplicationUserFavoriteGroup
        /// class.
        /// </summary>
        public ApplicationUserFavoriteGroup(Guid? id = default(Guid?), Guid? favoriteGuid = default(Guid?))
        {
            Id = id;
            FavoriteGuid = favoriteGuid;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public Guid? Id
        {
            get; set;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "favoriteGuid")]
        public Guid? FavoriteGuid
        {
            get; set;
        }

    }
}
