// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace SINners.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;

    public partial class SINnerVisibility
    {
        /// <summary>
        /// Initializes a new instance of the SINnerVisibility class.
        /// </summary>
        public SINnerVisibility()
        {
        }

        /// <summary>
        /// Initializes a new instance of the SINnerVisibility class.
        /// </summary>
        public SINnerVisibility(Guid? id = default(Guid?), bool? isPublic = default(bool?), bool? isGroupVisible = default(bool?), IList<SINnerUserRight> userRights = default(IList<SINnerUserRight>))
        {
            Id = id;
            IsPublic = isPublic;
            IsGroupVisible = isGroupVisible;
            UserRights = userRights;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public Guid? Id
        {
            get; set;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "isPublic")]
        public bool? IsPublic
        {
            get; set;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "isGroupVisible")]
        public bool? IsGroupVisible
        {
            get; set;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "userRights")]
        public IList<SINnerUserRight> UserRights
        {
            get; set;
        }

    }
}
